Add create v2Users
pokt-foundation/pocket-http-db pull request #170
Opened 2023-04-21 03:26 UTC by ricantar

2023-04-25 16:21 UTC, pablocampogo requested changes

2023-04-25 16:21 UTC, pablocampogo commented on cache/cache.go
> +		_, Derr := writer.DeletePortalUser(ctx, user.ID)
As a betterment for the future this should be in the same transaction of the DB

2023-04-25 16:21 UTC, pablocampogo commented on cache/cache.go
> +		_, Derr := writer.DeletePortalUser(ctx, user.ID)
Also make this err field private (starting in lower case)

2023-04-25 16:50 UTC, ricantar commented on cache/cache.go
> +		_, Derr := writer.DeletePortalUser(ctx, user.ID)
Yes, it should eb on the portal-db query, I'll add it as TODO

2023-04-25 18:29 UTC, commoddity requested changes
Just added a few questions on the PR. Overall approach is good but I think we should move the multiple DB operations to live inside the driver itself rather than inside the PHD cache method.

2023-04-25 18:29 UTC, commoddity commented on cache/cache.go
> +// GetAccounts returns all Accounts for a given user
A bit confused about this function implementation. It seems like this should only return a single User but instead it seems like it's returning a slice of AccountUserAccess. What is the intended functionality? And where is it intended to be used?

Also the comment needs to be updated.

2023-04-26 21:36 UTC, ricantar commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
Done

2023-04-28 01:30 UTC, ricantar commented on cache/cache.go
> +		// TODO: Make the rollback in the portal-db query
Done

2023-04-28 01:30 UTC, ricantar commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
FreetierV0 doesn't exist in the portal-db anymore, it was set to BasicPlan. Should I add it again ?

2023-04-28 01:33 UTC, commoddity commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
```
	BasicPlan      PayPlanType = "basic_plan"
	DeveloperPlan  PayPlanType = "developer_plan"
	EnterprisePlan PayPlanType = "enterprise_plan"
	ProPlan        PayPlanType = "pro_plan"
	StartupPlan    PayPlanType = "startup_plan"
	````

Oh those plans were only meant for the test data; they were just random plan string names I made and and were never meant to be updated in the actual code. As of right now we should be using all the plan types.

2023-04-28 01:35 UTC, commoddity commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
https://github.com/pokt-foundation/portal-db/pull/97/files 

This PR seems incorrect since we don't plan to change the plan types until after the V2 migration is all done.

2023-04-28 01:37 UTC, ricantar commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
I thought it was because the test were failing because of that. I'll change it anyways in the portal-db PR with the account creation

2023-04-28 18:17 UTC, commoddity commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
Yes because those plans are for use in the tests and only the tests.

The reason I used them is because post V2 migration the biz team will likely be creating new plans and so our tests plans should be test data that is agnostic to whatever the actual plans are in the production code.

2023-04-28 18:23 UTC, commoddity commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
Per our discussion in the Portal DB PR we can have the actual and test plans both exist in the test data but the test plans should still not exist in the non-test types package.

2023-04-28 19:07 UTC, ricantar commented on cache/cache.go
> +		_, Derr := writer.DeletePortalUser(ctx, user.ID)
btw: done

2023-04-28 19:08 UTC, ricantar commented on cache/cache.go
> +	newAccountInput := types.Account{PlanType: types.BasicPlan, CreatedAt: time.Now(), UpdatedAt: time.Now()}
Took a quick scan. It's only used in testing

2023-04-28 19:09 UTC, ricantar commented on router/router.go
> +func (rt *Router) GetUserByProviderID(w http.ResponseWriter, r *http.Request) {
removed too

2023-04-28 20:46 UTC, commoddity requested changes
This PR needs some changes to use the listener to perform creation of the user/account, as well as a number of other changes related to where the Writer is called.

2023-04-28 20:46 UTC, commoddity commented on cache/cache.go
> +	newUserID, err := writer.WriteUserNewSignUp(ctx, createUserInput, currentTime)
This part should happen in the `router.go` file. All creation of the entries in the DB should happen inside router.go as is the established pattern. That's why the Writer is a field on the Router struct; the Writer should not be passed as an argument and the `cache.go` logic should only be concerned with updating the state of the cache.

for reference, see:
https://github.com/pokt-foundation/pocket-http-db/blob/master/router/router.go#L532

2023-04-28 20:46 UTC, commoddity commented on cache/cache.go
> +	for _, account := range accounts {
This loop appears to be looping through every account in the cache which is not necessary. As the new Account is not yet present in the cache this would not accomplish the goal of updating anything related to the newly created Account in the cache. 

I would suggest updating the Portal DB method to return both the newly created Account (converted to a `types.Account` struct) as well as the newly created user ID. Once that is done the lines 

```
if _, ok := c.accountsByUserID[user.UserID]; !ok {
		c.accountsByUserID[user.UserID] = make(map[types.AccountID]*types.Account)
	}
	c.accountsByUserID[user.UserID][account.ID] = account
}

c.userIDs[createUserInput.ProviderUserID] = user.ID
```

should be sufficient to update the new Account in the cache as well as set the user ID to the userID map.

2023-04-28 20:46 UTC, commoddity commented on router/router.go
> +func (rt *Router) CreatePortalUser(w http.ResponseWriter, r *http.Request) {
As mentioned above, `rt.Writer` should be called here to perform DB write operations.

2023-04-28 20:46 UTC, commoddity commented on cache/cache.go
> +func (c *Cache) CreateNewPortalUser(ctx context.Context, writer driver.Writer, createUserInput types.CreateUser) (types.User, error) {
The way that the PHD cache works for added created entries is always via the listener. Therefore this should not be a public method and should be called in response to a listener notification rather than directly in the router.

For reference, see here:

https://github.com/pokt-foundation/pocket-http-db/blob/v2-staging/cache/cache.go#L503

`upsertPortalApp` is called in resposne to listener event here:

https://github.com/pokt-foundation/pocket-http-db/blob/v2-staging/cache/listener.go#L38


Without this flow, the newly created user and account will not be present in all instances of PHD, only the one where the `CreateNewPortalUser` is initially called.

Additionally, don't worry about making the `CreateNewPortalUser` into an upsert like for PortalApp; it will only be called to create the user and account, not to update them.

If you have any other questions about the PHD listener flow please message me about them on Discord.

2023-04-28 20:46 UTC, commoddity commented on main_e2e_test.go
> +				createdUser, err := ts.client1.CreatePortalUser(testCtx, test.userInput)
All E2E tests need to confirm the presence of the created object in both instances of PHD (client 1 and client2). If you add the client2 check to this test you will see the newly created user and account are not present (see my above comment about the listener).

2023-04-28 20:58 UTC, commoddity commented on cache/cache.go
> +	for _, account := range accounts {
Actually scratch this part:

"I would suggest updating the Portal DB method to return both the newly created Account (converted to a types.Account struct) as well as the newly created user ID. Once that is done the lines"

You will actuallly need two separate cache method, one in response to each listener event: one for Accounts and one for the new user add the user ID to map.

2023-04-30 21:16 UTC, ricantar commented on cache/cache.go
> +	newUserID, err := writer.WriteUserNewSignUp(ctx, createUserInput, currentTime)
I think we'll have to sync up. The pattern used in `v2-staging` is to send the writter to the cache and then call it inside the cache package. That change was introduced 4w ago, I can change it anyways, but that's not what PHD it's doing right now

2023-04-30 21:17 UTC, ricantar commented on cache/cache.go
> +func (c *Cache) CreateNewPortalUser(ctx context.Context, writer driver.Writer, createUserInput types.CreateUser) (types.User, error) {
Yeah, I forgot about the listener, I'll have to change that.

2023-04-30 21:19 UTC, ricantar commented on cache/cache.go
> +	for _, account := range accounts {
I have to go through the accounts because we don't know what account was created, we only have the `userID`

2023-05-01 16:10 UTC, commoddity commented on cache/cache.go
> +	for _, account := range accounts {
Makes sense in this context but as I mentioned above the addition of the Account and User to the cache should be in response to two separate listener events as is the pattern we use elsewhere in PHD.

2023-05-01 16:12 UTC, commoddity commented on cache/cache.go
> +	newUserID, err := writer.WriteUserNewSignUp(ctx, createUserInput, currentTime)
Ah I see where the confusion may have come from: for the legacy types the patter is to pass the Writer to the legacy adaptors as a sort of temporary workaround until we start using the V2 structs. 

However since the User is a new data type for V2 with no legacy equivalent we should call the Writer inside the router as is currently done in PHD V1 (that's why I showed a V1 Router method as the example above). IF you want to sync up today to discuss this I'm available; just ping me on discord.

2023-05-04 20:16 UTC, ricantar commented on cache/cache.go
> +func (c *Cache) CreateNewPortalUser(ctx context.Context, writer driver.Writer, createUserInput types.CreateUser) (types.User, error) {
Done

2023-05-04 20:16 UTC, ricantar commented on cache/cache.go
> +	newUserID, err := writer.WriteUserNewSignUp(ctx, createUserInput, currentTime)
Updated

2023-05-04 20:17 UTC, ricantar commented on cache/cache.go
> +	for _, account := range accounts {
Done

2023-05-04 20:18 UTC, ricantar commented on main_e2e_test.go
> +				createdUser, err := ts.client1.CreatePortalUser(testCtx, test.userInput)
Done

2023-05-04 21:20 UTC, pablocampogo approved these changes

2023-05-08 17:31 UTC, commoddity commented on cache/cache.go
> +	v1Types "github.com/pokt-foundation/portal-db/types"
I don't believe the V2 cache should have any types from V1. Is there a reason this needs to be V1?

2023-05-08 17:33 UTC, commoddity commented on cache/cache.go
> +func (c *Cache) addUserAuthProviders(userAuth types.UserAuthProvider) {
Should be singular (`addUserAuthProvider`)

2023-05-08 17:33 UTC, commoddity commented on cache/cache_legacy_adapter.go
> +	v1Types "github.com/pokt-foundation/portal-db/types"
Good update here.

2023-05-08 17:34 UTC, commoddity commented on cache/cache_legacy_adapter.go
> +				lbID := v1Types.LoadBalancerID(portalApp.ID)
Nice update, TY.

2023-05-08 17:38 UTC, commoddity commented on router/router.go
> +	NewUser, accID, err := rt.writer.WriteUserNewSignUp(r.Context(), userInput, time.Now())
`NewUser` should be in camel case. 

Also would prefer `accountID` be fully spelled out for clarity, WDYT?

2023-05-08 19:54 UTC, ricantar commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
Yes, for the `legacy_adapter` since loadblancer struct uses a v1 PayPlanType. We'll need this just for now

2023-05-08 19:55 UTC, commoddity commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
Can we not just do the conversion in the legacy adaptor then?

2023-05-08 19:56 UTC, ricantar commented on router/router.go
> +	NewUser, accID, err := rt.writer.WriteUserNewSignUp(r.Context(), userInput, time.Now())
Agree

2023-05-08 19:57 UTC, ricantar commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
As dumb as it can sound: I didn't want to touch the `legacy_adapter` code, but that's a better idea actully. Done

2023-05-08 19:58 UTC, commoddity commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
Thanks. :) would just prefer to keep all the V1 stuff out of the V2 cache. That's what the adapter is for.

2023-05-08 19:59 UTC, ricantar commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
Done, running tests

2023-05-08 20:23 UTC, ricantar commented on cache/cache.go
> +		plans map[v1Types.PayPlanType]*types.Plan
Done

2023-05-08 20:23 UTC, ricantar commented on cache/cache.go
> +	// Convert old payplan to new payplans
done

2023-05-08 20:36 UTC, commoddity approved these changes

2023-05-08 20:48 UTC, merged