T-14768 Support listener changes
pokt-foundation/pocket-http-db pull request #54
Opened 2022-10-17 14:30 UTC by pablocampogo

- Add changes for supporting listener from PG DB
- Change cache updates and adds to be private and just change what comes directly from the table
- Change the router to return the same it was returning from the cache change without actually doing it
- Add cache updates with retries for the side tables (they need to retry until the main table change is up)
- Made updates simpler to just update the pointer once (this way they're less buggy, although we need to add each possible field that could change)
- Solved various bugs found making the e2e pass

2022-10-20 20:31 UTC, commoddity approved these changes
Looks good.

2022-10-20 20:36 UTC, adshmh requested changes
Thank you for the PR!
Some minor changes, LGTM otherwise.

2022-10-20 20:36 UTC, adshmh commented on cache/cache.go
> +	c.addGatewaySettingsWithRetries(settings, retries)
This isn't a good candidate for recursion IMO: increasing the number of retries will have a direct impact on amount of resources through stack trace.

2022-10-20 20:36 UTC, adshmh commented on cache/cache.go
> +	c.addNotificationSettingsWithRetries(settings, retries)
Same as previous comment re recursion. A loop is both more readable and has a smaller resource footprint.

2022-10-20 20:36 UTC, adshmh commented on cache/cache.go
> +func (c *Cache) addLoadBalancer(lb *repository.LoadBalancer) {
Same as previous comments regarding references. This method should construct/modify its own copy of the object, which itself is also passed by value

2022-10-20 20:36 UTC, adshmh commented on cache/cache.go
> +	c.addStickinessOptionsWithRetries(opts, retries)
Same comment as previous ones re recursion.

2022-10-20 20:52 UTC, pablocampogo commented on cache/listener.go
> +func (c *Cache) parseApplicationNotification(n *repository.Notification) {
This one is a pointer on purpose, on previous iterations I did need to pass changes between this functions, don't see it unlikely that will be the case again for notification

2022-10-20 20:54 UTC, pablocampogo commented on main.go
> +			fmt.Println(err.Error())
The only other thing we can log here is the event type

2022-10-20 20:54 UTC, commoddity commented on tests/e2e_test.go
> +	_, err := exec.Command("docker", "compose", "up", "-d", "--build", "--force-recreate").Output()
SG. Just curious where would be the desired place to set up the env?

2022-10-20 21:09 UTC, pablocampogo commented on router/router.go
> +		fullApp.PayPlanType = "" // set to empty to avoid two sources of truth
Some actual output structs should do the trick

2022-10-20 21:11 UTC, pablocampogo commented on cache/cache.go
> +func (c *Cache) updateBlockchain(inBlockchain *repository.Blockchain) {
I don't think is necessary to change all of them to be references (those are extra steps to then save it as a pointer anyways). I'll do another PR so we don't return pointers from cache.

2022-10-25 21:46 UTC, commoddity approved these changes
Looks good, thank you.

2022-10-26 15:26 UTC, adshmh requested changes
Thank you for updating the PR and addressing the review comments.
There are only a few more items to address (2 general categories really, with multiple instances)

2022-10-26 15:26 UTC, adshmh commented on cache/cache.go
> +	retriesSideTable = 5
Not a blocker, but we need a better name for this.

2022-10-26 15:26 UTC, adshmh commented on cache/cache.go
> +	for i := 0; i < retriesSideTable; i++ {
Could you please help me understand why there is a retry/loop here?
The code being run in the loop never returns an error. 
If we can't find the app identified by the `settings.ID`, why is there a need for a sleep and retry, instead of simply moving on?

2022-10-26 15:26 UTC, adshmh commented on cache/cache.go
> +func (c *Cache) updateApplication(inApp repository.Application) {
Thank you for removing the pass-by-reference!

2022-10-26 15:26 UTC, adshmh commented on cache/cache.go
> +		lb := c.GetLoadBalancer(lbApp.LbID)
Same question/comments as previous retry/loops and mutex calls.

2022-10-26 15:26 UTC, adshmh commented on cache/listener.go
> +func (c *Cache) parseGatewaySettingsNotification(n repository.Notification) {
This function is taking a `repository.Notification` input type and doing dynamic type-cast on it, assuming the cast will be OK.
Even though you have put a guard in place, i.e. the listener checks for the type before calling any of these functions, this practice could cause issues later, simply because the check on the input type is moved somewhere outside the function.

This function, and all other similar ones here, needs to get a correct signature to accept the type it needs, e.g. `repository.GatewaySettings` here, etc. The listener, which is performing the type check already, should perform the type cast before calling any of these functions.

2022-10-26 15:26 UTC, adshmh commented on cache/listener.go
> +func (c *Cache) parseLoadBalancerNotification(n repository.Notification) {
Same comment here as all the other functions that perform type casting on `Notification` data type: they need to accept exactly the type that they need: it is on the caller (listener object in this case) to cast to correct type, as that is precisely where the type check is being performed.

2022-10-26 15:26 UTC, adshmh commented on main.go
> +			fmt.Printf("Problem with listener, error: %s, event type: %d", err.Error(), ev)
Thank you for the more helpful error logging!

2022-10-26 15:41 UTC, pablocampogo commented on cache/cache.go
> +	for i := 0; i < retriesSideTable; i++ {
Because in the creation of records, a side table could arribe first from cache than the main table, and we have the cache in a way that the side tables need the main one. By retrying we give time for the main table creation to arrive

2022-10-26 15:44 UTC, pablocampogo commented on cache/cache.go
> +		blockchain := c.GetBlockchain(opts.BlockchainID)
Ah and also if I lock since the start the get functions wouldn't work, nonetheless they also have locks of their own

2022-10-26 15:51 UTC, pablocampogo commented on cache/listener.go
> +func (c *Cache) parseGatewaySettingsNotification(n repository.Notification) {
We can do this in other PR, I would like to do something with logs for it, in case the type cast fails (which it shouldn't)

2022-10-28 15:30 UTC, adshmh approved these changes
Thank you for addressing the comments on listener events.
As agreed, we need to address the typecast in the next PR.

2022-10-28 15:30 UTC, adshmh commented on cache/listener_test.go
> +	time.Sleep(1 * time.Second) // need time for cache refresh
Not a blocker, but this is another reason for using table-driven tests: they would allow parallelizing these tests, and avoid adding up the sleep time to total test time.

2022-10-28 18:08 UTC, commoddity approved these changes
LGTM - just some questions I'll discuss in Discord

2022-10-28 18:13 UTC, merged