T 15233 phd logs
pokt-foundation/pocket-http-db pull request #61
Opened 2022-10-31 17:34 UTC by ricantar

2022-10-31 18:00 UTC, commoddity reviewed
Looks like a good approach. 

Are you planning to add to the tests to verify that these log methods are getting called and the `interfaceToString` func is working correctly for all cases?

2022-10-31 18:02 UTC, ricantar commented on router/router.go
> +		logError("UpdateApplication in GetApplication failed", []interface{}{vars}, errApplicationNotFound)
You're right, sounds better

2022-10-31 18:10 UTC, ricantar commented
> Looks like a good approach.
> 
> Are you planning to add to the tests to verify that these log methods are getting called and the `interfaceToString` func is working correctly for all cases?

I tested these behavior locally but I'm not sure how to create those test using real scenarios. I could add dummy test for logError, but I'm 100% sure that the function is working

2022-10-31 18:41 UTC, ricantar commented
> This pull request **introduces 1 alert** when merging [1f41755](https://github.com/pokt-foundation/pocket-http-db/commit/1f417555c6229b42f71c2bb4a959c7a780ff1e77) into [1205353](https://github.com/pokt-foundation/pocket-http-db/commit/1205353159866ff271ff92110895d14c41ff4ff7) - [view on LGTM.com](https://lgtm.com/projects/g/pokt-foundation/pocket-http-db/rev/pr-0d726c6f6b79f5177e70ed0958d9f9c86b217921)
> 
> **new alerts:**
> 
> * 1 for Log entries created from user input

It's ok, we wan't to know what the user sent to trigger the error

2022-10-31 19:27 UTC, commoddity commented
Sounds good then, I think this is fine.

2022-10-31 19:47 UTC, adshmh requested changes
Thank you for the PR!
In addition to below review comments, could you please rebase to remove the merge commit (the very last one?).

2022-10-31 19:47 UTC, adshmh commented on cache/cache_test.go
> +	c.ErrorContains(err, "error on pay plans")
It may be a better approach to use `errors.Is` here.

2022-10-31 19:47 UTC, adshmh commented on cache/cache_test.go
> +	c.ErrorContains(err, "error on loadbalancers")
Same comment as previous ones regarding errors.

2022-10-31 19:47 UTC, adshmh commented on cache/listener.go
> +	errParseApplicationFailed          = errors.New("parse application failed")
Nice use of custom errors!

2022-10-31 19:47 UTC, adshmh commented on cache/listener.go
> +	log = logrus.New()
This needs to be passed to the listener, rather than instantiated directly.

2022-10-31 19:47 UTC, adshmh commented on cache/listener.go
> +func interfaceToString(inter interface{}) string {
Use of `interface{}` is not justified here. You can extend/enhance custom error types to provide more detailed errors and error messages.

2022-10-31 19:47 UTC, adshmh commented on cache/listener.go
> +		logError("parseApplicationNotification failed", []interface{}{n.Data}, errParseApplicationFailed)
Please see the review comment on use of empty interfaces. This is converting something to an empty interface, only to reverse that conversion later. One common alternative is to use custom errors (IMO any other approach could also be considered, just not empty interfaces)

2022-10-31 19:47 UTC, adshmh commented on cache/listener.go
> +		logError("parseLbApps failed", []interface{}{n.Data}, errParseLBAppsFailed)
For this, and all other calls for logging errors, we can use custom errors (and extend as much as needed).
The `logError` could then use the instantiated logger and the custom errors String() method to write the log entry.

2022-10-31 19:47 UTC, adshmh commented on router/router.go
> +			logError("UpdateApplication failed", []interface{}{updateInput}, err)
Please see previous comments on empty interfaces and casting to them and back to strings.

2022-10-31 20:31 UTC, ricantar commented on cache/cache_test.go
> +	c.ErrorContains(err, "error on redirects")
In this test the error is not an "error" is a mock, I'll change those mock messages to use an error and then compare this error with the expected one

2022-10-31 20:32 UTC, ricantar commented on cache/cache_test.go
> +	c.ErrorContains(err, "error on loadbalancers")
Same as previous

2022-10-31 20:33 UTC, ricantar commented on cache/listener.go
> +	log = logrus.New()
mmm I like it. Thanks!

2022-10-31 21:04 UTC, ricantar commented on cache/listener.go
> +func logError(msg string, inputs []interface{}, err error) {
You're right. I tried to use a more general approach so we could use this function in the utils package, but since it's not there yet I should change it for now.

2022-11-03 19:23 UTC, ricantar commented on cache/cache_test.go
> +	c.ErrorContains(err, "error on pay plans")
Fixed in the last commit

2022-11-03 19:24 UTC, ricantar commented on cache/listener.go
> +func logError(msg string, inputs []interface{}, err error) {
I finally removed the "inputs" for know, and just let a single error with the propper format

2022-11-03 22:52 UTC, commoddity requested changes

2022-11-03 22:52 UTC, commoddity commented on router/router.go
>  	cache := cache.NewCache(reader)
I think we should be passing the logger to `NewCache` as a parameter here, rather than as a parameter to `SetCache` below.

2022-11-03 22:52 UTC, commoddity commented on cache/cache.go
>  // NewCache returns cache instance from reader interface
`NewCache` should take the logger as a parameter which is then passes to the instance of cache.

2022-11-03 22:52 UTC, commoddity commented on cache/listener.go
> +	if c.log == nil {
I think that a single logger instance should be created at the top level inside `main.go` and then passed down as a struct field to the Cache rather than being instantiated inside this func. This also avoids the need to pass the logger as a parameter anywhere except inside the NewCache and NewRouter funcs.

2022-11-03 22:52 UTC, commoddity commented on cache/listener.go
> +	"github.com/sirupsen/logrus"
Super minor comment but in all the other repos we alias logrus as `logger` like `logger "github.com/sirupsen/logrus"`. if we could do that here would making this package consistent across all of our repos.

2022-11-03 22:52 UTC, commoddity commented on cache/listener.go
> +	c.log = logger
As mentioned in other comments, if we can instantiate a single instance of logrus inside `main.go` and pass it down to the funcs that create the Cache and Router would be preferred vs instantiating in multiple places like is being done here.

2022-11-03 23:05 UTC, ricantar commented on cache/listener.go
> +	"github.com/sirupsen/logrus"
I don't think that we should keep doing that since we're creation a propper `logger` in `portal-relayer-global-services`

2022-11-03 23:07 UTC, commoddity commented on cache/listener.go
> +	"github.com/sirupsen/logrus"
Ah I didn't know about that. No problem then, that's not a blocker at all.

2022-11-03 23:07 UTC, ricantar commented on cache/listener.go
> +	c.log = logger
It's being passed, as you can see logger is a pointer, so it's being referenced to the logger created in `main.go`

2022-11-03 23:08 UTC, ricantar commented on router/router.go
>  	cache := cache.NewCache(reader)
I moved the logger reference to `SetCache` because is being used in both places, `main.go` and `router.go`, but there's I can move it to `NewCache`

2022-11-03 23:09 UTC, commoddity commented on cache/listener.go
> +	c.log = logger
Makes sense, but why pass it down multiple times as a parameter when it could just be assigned inside the func that creates the Cache?

2022-11-03 23:14 UTC, ricantar commented on cache/listener.go
> +	c.log = logger
It's passed only once, in SetCache, and then again for the listener. Bute sure, I can move it to createCache

2022-11-03 23:16 UTC, ricantar commented on cache/listener.go
> +	c.log = logger
Done, pushed change

2022-11-03 23:19 UTC, commoddity commented on cache/listener.go
> +	c.log = logger
Thank you, appreciate the changes.

2022-11-03 23:19 UTC, commoddity commented on router/router.go
>  	cache := cache.NewCache(reader)
Thank you.

2022-11-04 16:55 UTC, commoddity commented on cache/listener.go
> +	if c.log == nil {
I think we can remove this if statement since the logger is assigned when the Cache is first created, right?

2022-11-04 16:57 UTC, commoddity commented on router/router.go
> +	if rt.log == nil {
Same comment as above, unless I'm mistaken, I don't think this if statement is needed anymore since the logger much be passed to the Router when it's first created.

2022-11-04 16:58 UTC, commoddity requested changes
Looks good to me. Just those two comments I made today and then I'm good with approving and merging.

2022-11-04 17:58 UTC, ricantar commented on cache/listener.go
> +	if c.log == nil {
It's an insurance to prevent nills if some how, someone uses de cache{} instead of newCache. But we can take that risk

2022-11-04 19:33 UTC, commoddity approved these changes
LGTM. Up to you if you want to merge on a Friday or wait until Monday.

2022-11-04 19:35 UTC, ricantar commented
> LGTM. Up to you if you want to merge on a Friday or wait until Monday.

We still need to wait for Arash, since it's a log change it doesn't matter too much, buuuut I would preffer to wait

2022-11-07 22:01 UTC, adshmh approved these changes
Thank you for addressing the review comments. LGTM

2022-11-07 22:52 UTC, merged