chore: remove unintended binary
pokt-foundation/pocket-http-db pull request #87
Opened 2023-01-17 18:00 UTC by commoddity

2023-01-25 21:25 UTC, ricantar approved these changes
Sweet

2023-01-25 21:52 UTC, adshmh requested changes
Thank you for the update. This is a great improvement over the previous PR: most of the added code is in a single file and is for e2e testing. Just a few suggestions (if followed, could significantly reduce the amount of actual code added here)

2023-01-25 21:52 UTC, adshmh commented on main.go
> +	_ "net/http/pprof"
Is this needed?

2023-01-25 21:52 UTC, adshmh commented on main.go
> +		time.Sleep(time.Duration(cacheRefresh) * time.Minute)
time.Sleep, should be avoided whenever possible, especially when the expected sleep time is in minutes.
[time.After](https://pkg.go.dev/time#After) is commonly used for this scenario.

2023-01-25 21:52 UTC, adshmh commented on main.go
> +		time.Sleep(time.Duration(cacheRefresh) * time.Minute)
In addition, it seems something that is an internal details of the `router` performed by an external function.
An internal method on the router itself (with a better name, e.g. `CacheRefresh()` run in its own go routine seems a better choice.

2023-01-25 21:52 UTC, adshmh commented on main.go
> +	go v0CacheHandler(v0Router, options.cacheRefresh, log)
Please see above review comment regarding this method and the corresponding one for v1.

2023-01-25 21:52 UTC, adshmh commented on main_e2e_v1_test.go
> +type DBClientTestSuite struct {
Not a blocker, but this does not really need to be an exported type.

2023-01-25 21:52 UTC, adshmh commented on main_e2e_v1_test.go
> +									ApplicationPublicKey: "test_11b8d394ca331d7c7a71ca1896d630f6",
Not a blocker, but moving all this data to json-formatted files with reasonable names under testdata directory will make this code more readable.

2023-01-25 21:52 UTC, adshmh commented on main_e2e_v1_test.go
> +				ts.Equal(test.application.Status, application.Status)
Is it possible to use a library for this, e.g. https://github.com/google/go-cmp, as we do with other repositories, to reduce the large number of comparisons?

2023-01-25 23:30 UTC, ezeike approved these changes
These PRs are much clearer. Looks good to me.

2023-01-26 00:39 UTC, commoddity commented on main.go
> +	_ "net/http/pprof"
Nope, that's for the memory profiler. Good catch; I will remove.

2023-01-26 00:39 UTC, commoddity commented on main.go
> +		time.Sleep(time.Duration(cacheRefresh) * time.Minute)
Sounds good. I suggest we do this in a separate PR  as this is not related to the v1 change (this is how the cache refresh has worked since we first created PHD).

2023-01-26 00:39 UTC, commoddity commented on main.go
> +	go v0CacheHandler(v0Router, options.cacheRefresh, log)
This is regarding the `time.Sleep` call?

2023-01-26 00:39 UTC, commoddity commented on main_e2e_v1_test.go
> +type DBClientTestSuite struct {
Agreed; I'll update to be unexported.

2023-01-26 00:39 UTC, commoddity commented on main_e2e_v1_test.go
> +									ApplicationPublicKey: "test_11b8d394ca331d7c7a71ca1896d630f6",
Agreed; I actually have a suggestion for reducing duplication of test data for the PHD test docker container but I suggest we discuss that in another context as it can be an eventual improvement after this PR is merged. WDYT?

2023-01-26 00:39 UTC, commoddity commented on main_e2e_v1_test.go
> +				ts.Equal(test.application.Status, application.Status)
The only issue with this is that the timestamps (`CreatedAt`, `UpdatedAt`) don't match and are not deterministic since the record is created by the test; otherwise I would just compare the entire structs. Open to a more readable approach for sure but again I suggest we do this in a subsequent PR.

2023-01-26 00:41 UTC, commoddity commented on main.go
> +		time.Sleep(time.Duration(cacheRefresh) * time.Minute)
@pablocampogo WDYT?

2023-01-26 00:50 UTC, adshmh commented on main.go
> +	go v0CacheHandler(v0Router, options.cacheRefresh, log)
No, it is regarding the this item: ```In addition, it seems something that is an internal details of the router performed by an external function.
An internal method on the router itself (with a better name, e.g. CacheRefresh() run in its own go routine seems a better choice.```

2023-01-26 00:51 UTC, commoddity commented on main.go
> +	go v0CacheHandler(v0Router, options.cacheRefresh, log)
Ah gotcha. Yeah I agree that implementation can be improved but still suggest we don't do it in this PR.

2023-01-26 00:52 UTC, adshmh commented on main_e2e_v1_test.go
> +				ts.Equal(test.application.Status, application.Status)
Sure, handling this on a seaparate PR is OK.

2023-01-26 16:05 UTC, commoddity commented on main.go
> +		time.Sleep(time.Duration(cacheRefresh) * time.Minute)
Added to Height, resolving this conversation.

2023-01-26 17:03 UTC, adshmh approved these changes
LGTM

2023-01-26 17:03 UTC, adshmh commented on cache/listener.go
> +		// nil check is needed because the v1 DB alerts will send a nil notification for user_access table
Not a blocker: this needs a unit test to cover the case the driver returns a nil notification.

2023-01-26 17:33 UTC, commoddity commented on cache/listener.go
> +		// nil check is needed because the v1 DB alerts will send a nil notification for user_access table
Noted, will add afterwards.

2023-01-26 17:43 UTC, merged