T-17793: V1 test adjustment
pokt-foundation/pocket-http-db pull request #88
Opened 2023-01-19 07:45 UTC by ricantar

- Update test for new v1 verstion

2023-01-19 19:01 UTC, commoddity commented on router/router.go
> +	rt.Router.HandleFunc("/v1/redirect", rt.CreateRedirect).Methods(http.MethodPost)
Just a quick FYI on this one: I changed this endpoint to `/v1/blockchain/redirect` as it should have been that from the start, so this endpoint won't be needed. 

There's just one place that this needs to be updated which is the `new-chains-ci` repo.

2023-01-19 19:07 UTC, commoddity commented on cache/mock.go
> +
These methods shouldn't be needed as they already exists on the `driver.MockDriver` struct provided by the `portal-db` repo.

2023-01-19 19:09 UTC, commoddity commented on tests/e2e_testdata.go
> -//go:build tests
The build tag should stay as we don't want this data to get compiled into the final binary.

2023-01-19 19:11 UTC, commoddity commented
Looks good aside from the comment I already made in the changed files. Thank you for this PR.

2023-01-20 17:37 UTC, ricantar commented on router/router.go
> +	rt.Router.HandleFunc("/v1/redirect", rt.CreateRedirect).Methods(http.MethodPost)
Good. Thank you for letting me know

2023-01-21 01:42 UTC, commoddity requested changes
Left some comments for requested changes before we can merge this one.

2023-01-21 03:15 UTC, ricantar commented on cache/mock.go
> +
Unfortunately, we need it as the driver uses a different implementation and doesn't work (tried and doesn't work)

2023-01-21 16:18 UTC, commoddity commented on cache/mock.go
> +
I just tested on my local workstation ad seem to work fine without them. I've pushed a few updates I had to make to the test schema get it working on this branch.

2023-01-21 16:36 UTC, commoddity commented
Pushed a few updates to the DB schema to get the test containers to start up correctly and added the `tests` build tag to get the new `v1` tests to run. 

Unfortunately it seems like the tests that hit the V1 endpoints are not working (failing on the `update` applications one). Let's dig into that on Monday though; signing off for the weekend.

2023-01-23 23:34 UTC, merged